import { writeFile, readFile, mkdir, rename } from 'node:fs/promises';
import * as path from 'node:path';

/** Marker comment to identify generated AGENTS.md files */
const GENERATED_MARKER = '<!-- Generated by agents-reverse-engineer -->';

/**
 * Check if an AGENTS.md file was generated by us (contains marker).
 */
async function isGeneratedAgentsMd(filePath: string): Promise<boolean> {
  try {
    const content = await readFile(filePath, 'utf-8');
    return content.includes(GENERATED_MARKER);
  } catch {
    return false;
  }
}

/**
 * Write AGENTS.md for a directory with LLM-generated content.
 *
 * If a user-defined AGENTS.md exists (not generated by us), it will be
 * preserved as AGENTS.local.md and referenced in the generated file.
 *
 * @param dirPath - Directory to write AGENTS.md for
 * @param projectRoot - Project root for relative paths
 * @param content - LLM-generated AGENTS.md content
 * @returns Path to written AGENTS.md
 */
export async function writeAgentsMd(
  dirPath: string,
  _projectRoot: string,
  content: string,
): Promise<string> {
  const agentsPath = path.join(dirPath, 'AGENTS.md');
  const localPath = path.join(dirPath, 'AGENTS.local.md');

  // Check if existing AGENTS.md is user-defined (not generated by us)
  try {
    const existingIsGenerated = await isGeneratedAgentsMd(agentsPath);
    if (!existingIsGenerated) {
      // User-defined AGENTS.md exists - preserve it
      await rename(agentsPath, localPath);
    }
  } catch {
    // No existing AGENTS.md - that's fine
  }

  // Ensure generated marker is present (LLM is instructed to include it,
  // but add safety net in case it doesn't)
  let finalContent = content;
  if (!finalContent.startsWith(GENERATED_MARKER)) {
    finalContent = `${GENERATED_MARKER}\n\n${finalContent}`;
  }

  await mkdir(path.dirname(agentsPath), { recursive: true });
  await writeFile(agentsPath, finalContent, 'utf-8');

  return agentsPath;
}
