import { writeFile, readFile, mkdir, rename } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import * as path from 'node:path';

/** Marker comment to identify generated AGENTS.md files */
export const GENERATED_MARKER = '<!-- Generated by agents-reverse-engineer -->';

/**
 * Check if an AGENTS.md file was generated by us (contains marker).
 */
export async function isGeneratedAgentsMd(filePath: string): Promise<boolean> {
  try {
    const content = await readFile(filePath, 'utf-8');
    return content.includes(GENERATED_MARKER);
  } catch {
    return false;
  }
}

/**
 * Write AGENTS.md for a directory with LLM-generated content.
 *
 * If a user-defined AGENTS.md exists (not generated by us), it will be
 * preserved as AGENTS.local.md. The user content is then prepended
 * verbatim above the generated content so AI agents see it first.
 *
 * @param dirPath - Directory to write AGENTS.md for
 * @param projectRoot - Project root for relative paths
 * @param content - LLM-generated AGENTS.md content
 * @returns Path to written AGENTS.md
 */
export async function writeAgentsMd(
  dirPath: string,
  _projectRoot: string,
  content: string,
): Promise<string> {
  const agentsPath = path.join(dirPath, 'AGENTS.md');
  const localPath = path.join(dirPath, 'AGENTS.local.md');

  // Step 1: Preserve user-authored AGENTS.md (rename to AGENTS.local.md)
  let hasLocalContent = false;
  try {
    const existingContent = await readFile(agentsPath, 'utf-8');
    if (!existingContent.includes(GENERATED_MARKER)) {
      await rename(agentsPath, localPath);
      hasLocalContent = true;
    }
  } catch {
    // No existing AGENTS.md
  }

  // Step 2: Check for already-renamed AGENTS.local.md (from a previous run)
  if (!hasLocalContent && existsSync(localPath)) {
    hasLocalContent = true;
  }

  // Step 3: Strip marker from LLM content (we add it ourselves)
  let llmContent = content;
  if (llmContent.startsWith(GENERATED_MARKER)) {
    llmContent = llmContent.slice(GENERATED_MARKER.length).replace(/^\n+/, '');
  }

  // Step 4: Build final content with marker + optional @import + LLM content
  const parts: string[] = [GENERATED_MARKER, ''];

  if (hasLocalContent) {
    parts.push('@AGENTS.local.md', '');
  }

  parts.push(llmContent);

  const finalContent = parts.join('\n');

  await mkdir(path.dirname(agentsPath), { recursive: true });
  await writeFile(agentsPath, finalContent, 'utf-8');

  return agentsPath;
}
