import { writeFile, readFile, stat, rename } from 'node:fs/promises';
import * as path from 'node:path';
import { isRuntimeInstalledLocally } from '../../installer/paths.js';

/** Marker comment to identify generated CLAUDE.md files */
const GENERATED_MARKER = '<!-- Generated by agents-reverse-engineer -->';

/**
 * Standard CLAUDE.md content - simple pointer to AGENTS.md.
 *
 * Per CONTEXT.md: "Simple pointer to AGENTS.md for Anthropic compatibility"
 */
function buildClaudeMdContent(hasLocalFile: boolean): string {
  const sections: string[] = [];

  // Generated marker (first line)
  sections.push(GENERATED_MARKER);
  sections.push('');

  // Reference to user-defined local file if it exists
  if (hasLocalFile) {
    sections.push('> **Note:** This project has additional documentation in [CLAUDE.local.md](./CLAUDE.local.md)');
    sections.push('');
  }

  sections.push('# CLAUDE.md');
  sections.push('');
  sections.push('See [AGENTS.md](./AGENTS.md) for codebase documentation.');
  sections.push('');
  sections.push('This file exists for Anthropic compatibility. The actual documentation');
  sections.push('is maintained in AGENTS.md files throughout the codebase.');
  sections.push('');

  return sections.join('\n');
}

/**
 * Check if a file was generated by us (contains marker).
 */
async function isGeneratedFile(filePath: string): Promise<boolean> {
  try {
    const content = await readFile(filePath, 'utf-8');
    return content.includes(GENERATED_MARKER);
  } catch {
    return false;
  }
}

/**
 * Check if a local file exists.
 */
async function hasLocalFile(localPath: string): Promise<boolean> {
  try {
    await stat(localPath);
    return true;
  } catch {
    return false;
  }
}

/**
 * Write CLAUDE.md at the project root.
 *
 * Only writes if Claude Code is installed locally (`.claude` directory exists).
 * If a user-defined CLAUDE.md exists (not generated by us), it will be
 * preserved as CLAUDE.local.md and referenced in the generated file.
 *
 * @param projectRoot - Project root directory
 * @returns Path to written CLAUDE.md, or null if Claude Code is not installed
 */
export async function writeClaudeMd(projectRoot: string): Promise<string | null> {
  // Only generate if Claude Code is installed locally
  const isInstalled = await isRuntimeInstalledLocally('claude', projectRoot);
  if (!isInstalled) {
    return null;
  }

  const claudePath = path.join(projectRoot, 'CLAUDE.md');
  const localPath = path.join(projectRoot, 'CLAUDE.local.md');

  // Check if existing CLAUDE.md is user-defined (not generated by us)
  let hasLocal = await hasLocalFile(localPath);

  try {
    const existingIsGenerated = await isGeneratedFile(claudePath);
    if (!existingIsGenerated) {
      // User-defined CLAUDE.md exists - preserve it
      await rename(claudePath, localPath);
      hasLocal = true;
    }
  } catch {
    // No existing CLAUDE.md - that's fine
  }

  const content = buildClaudeMdContent(hasLocal);
  await writeFile(claudePath, content, 'utf-8');

  return claudePath;
}

/**
 * Get the content that would be written to CLAUDE.md.
 * Useful for previewing without writing.
 */
export function getClaudeMdContent(): string {
  return buildClaudeMdContent(false);
}
