import { writeFile, readFile, stat, rename } from 'node:fs/promises';
import * as path from 'node:path';
import { isRuntimeInstalledLocally } from '../../installer/paths.js';

/** Marker comment to identify generated GEMINI.md files */
const GENERATED_MARKER = '<!-- Generated by agents-reverse-engineer -->';

/**
 * Standard GEMINI.md content - simple pointer to AGENTS.md.
 *
 * For Google Gemini CLI compatibility.
 */
function buildGeminiMdContent(hasLocalFile: boolean): string {
  const sections: string[] = [];

  // Generated marker (first line)
  sections.push(GENERATED_MARKER);
  sections.push('');

  // Reference to user-defined local file if it exists
  if (hasLocalFile) {
    sections.push('> **Note:** This project has additional documentation in [GEMINI.local.md](./GEMINI.local.md)');
    sections.push('');
  }

  sections.push('# GEMINI.md');
  sections.push('');
  sections.push('See [AGENTS.md](./AGENTS.md) for codebase documentation.');
  sections.push('');
  sections.push('This file exists for Google Gemini CLI compatibility. The actual documentation');
  sections.push('is maintained in AGENTS.md files throughout the codebase.');
  sections.push('');

  return sections.join('\n');
}

/**
 * Check if a file was generated by us (contains marker).
 */
async function isGeneratedFile(filePath: string): Promise<boolean> {
  try {
    const content = await readFile(filePath, 'utf-8');
    return content.includes(GENERATED_MARKER);
  } catch {
    return false;
  }
}

/**
 * Check if a local file exists.
 */
async function hasLocalFile(localPath: string): Promise<boolean> {
  try {
    await stat(localPath);
    return true;
  } catch {
    return false;
  }
}

/**
 * Write GEMINI.md at the project root.
 *
 * Only writes if Gemini CLI is installed locally (`.gemini` directory exists).
 * If a user-defined GEMINI.md exists (not generated by us), it will be
 * preserved as GEMINI.local.md and referenced in the generated file.
 *
 * @param projectRoot - Project root directory
 * @returns Path to written GEMINI.md, or null if Gemini CLI is not installed
 */
export async function writeGeminiMd(projectRoot: string): Promise<string | null> {
  // Only generate if Gemini CLI is installed locally
  const isInstalled = await isRuntimeInstalledLocally('gemini', projectRoot);
  if (!isInstalled) {
    return null;
  }

  const geminiPath = path.join(projectRoot, 'GEMINI.md');
  const localPath = path.join(projectRoot, 'GEMINI.local.md');

  // Check if existing GEMINI.md is user-defined (not generated by us)
  let hasLocal = await hasLocalFile(localPath);

  try {
    const existingIsGenerated = await isGeneratedFile(geminiPath);
    if (!existingIsGenerated) {
      // User-defined GEMINI.md exists - preserve it
      await rename(geminiPath, localPath);
      hasLocal = true;
    }
  } catch {
    // No existing GEMINI.md - that's fine
  }

  const content = buildGeminiMdContent(hasLocal);
  await writeFile(geminiPath, content, 'utf-8');

  return geminiPath;
}

/**
 * Get the content that would be written to GEMINI.md.
 * Useful for previewing without writing.
 */
export function getGeminiMdContent(): string {
  return buildGeminiMdContent(false);
}
