import { writeFile, readFile, stat, rename } from 'node:fs/promises';
import * as path from 'node:path';
import { isRuntimeInstalledLocally } from '../../installer/paths.js';

/** Marker comment to identify generated OPENCODE.md files */
const GENERATED_MARKER = '<!-- Generated by agents-reverse-engineer -->';

/**
 * Standard OPENCODE.md content - simple pointer to AGENTS.md.
 *
 * For OpenCode compatibility.
 */
function buildOpencodeMdContent(hasLocalFile: boolean): string {
  const sections: string[] = [];

  // Generated marker (first line)
  sections.push(GENERATED_MARKER);
  sections.push('');

  // Reference to user-defined local file if it exists
  if (hasLocalFile) {
    sections.push('> **Note:** This project has additional documentation in [OPENCODE.local.md](./OPENCODE.local.md)');
    sections.push('');
  }

  sections.push('# OPENCODE.md');
  sections.push('');
  sections.push('See [AGENTS.md](./AGENTS.md) for codebase documentation.');
  sections.push('');
  sections.push('This file exists for OpenCode compatibility. The actual documentation');
  sections.push('is maintained in AGENTS.md files throughout the codebase.');
  sections.push('');

  return sections.join('\n');
}

/**
 * Check if a file was generated by us (contains marker).
 */
async function isGeneratedFile(filePath: string): Promise<boolean> {
  try {
    const content = await readFile(filePath, 'utf-8');
    return content.includes(GENERATED_MARKER);
  } catch {
    return false;
  }
}

/**
 * Check if a local file exists.
 */
async function hasLocalFile(localPath: string): Promise<boolean> {
  try {
    await stat(localPath);
    return true;
  } catch {
    return false;
  }
}

/**
 * Write OPENCODE.md at the project root.
 *
 * Only writes if OpenCode is installed locally (`.opencode` directory exists).
 * If a user-defined OPENCODE.md exists (not generated by us), it will be
 * preserved as OPENCODE.local.md and referenced in the generated file.
 *
 * @param projectRoot - Project root directory
 * @returns Path to written OPENCODE.md, or null if OpenCode is not installed
 */
export async function writeOpencodeMd(projectRoot: string): Promise<string | null> {
  // Only generate if OpenCode is installed locally
  const isInstalled = await isRuntimeInstalledLocally('opencode', projectRoot);
  if (!isInstalled) {
    return null;
  }

  const opencodePath = path.join(projectRoot, 'OPENCODE.md');
  const localPath = path.join(projectRoot, 'OPENCODE.local.md');

  // Check if existing OPENCODE.md is user-defined (not generated by us)
  let hasLocal = await hasLocalFile(localPath);

  try {
    const existingIsGenerated = await isGeneratedFile(opencodePath);
    if (!existingIsGenerated) {
      // User-defined OPENCODE.md exists - preserve it
      await rename(opencodePath, localPath);
      hasLocal = true;
    }
  } catch {
    // No existing OPENCODE.md - that's fine
  }

  const content = buildOpencodeMdContent(hasLocal);
  await writeFile(opencodePath, content, 'utf-8');

  return opencodePath;
}

/**
 * Get the content that would be written to OPENCODE.md.
 * Useful for previewing without writing.
 */
export function getOpencodeMdContent(): string {
  return buildOpencodeMdContent(false);
}
