/**
 * Template generators for AI coding assistant integration files
 *
 * Generates command file templates for Claude Code, OpenCode, Gemini CLI, and session hooks.
 */

import type { IntegrationTemplate } from './types.js';

// =============================================================================
// Shared Command Content
// =============================================================================

const COMMANDS = {
  generate: {
    description: 'Generate AI-friendly documentation for the entire codebase',
    argumentHint: '[path] [--budget N] [--dry-run] [--concurrency N] [--verbose] [--quiet] [--fail-fast] [--debug] [--trace]',
    content: `Generate comprehensive documentation for this codebase using agents-reverse-engineer.

<execution>
Run the agents-reverse-engineer generate command:

\`\`\`bash
npx agents-reverse-engineer@latest generate $ARGUMENTS
\`\`\`

This executes a three-phase pipeline:

1. **Discovery & Planning**: Walks the directory tree, applies filters (gitignore, vendor, binary, custom), detects file types, and creates a generation plan with token budget tracking.

2. **File Analysis** (concurrent): Analyzes each source file via AI and writes \`.sum\` summary files with YAML frontmatter (\`content_hash\`, \`file_type\`, \`purpose\`, \`public_interface\`, \`dependencies\`, \`patterns\`).

3. **Directory & Root Documents** (sequential):
   - Generates \`AGENTS.md\` per directory in post-order traversal (deepest first, so child summaries feed into parents)
   - Creates root documents: \`CLAUDE.md\`, \`ARCHITECTURE.md\` (if 20+ source files)
   - Creates per-package documents at each manifest location (package.json, go.mod, Cargo.toml): \`STACK.md\`, \`STRUCTURE.md\`, \`CONVENTIONS.md\`, \`TESTING.md\`, \`INTEGRATIONS.md\`, \`CONCERNS.md\`

**Options:**
- \`--dry-run\`: Preview the plan without making AI calls
- \`--budget N\`: Override token budget
- \`--concurrency N\`: Control number of parallel AI calls (default: 5)
- \`--fail-fast\`: Stop on first file analysis failure
- \`--debug\`: Show AI prompts and backend details
- \`--trace\`: Enable concurrency tracing to \`.agents-reverse-engineer/traces/\`
- \`--verbose\`: Show detailed task breakdown
- \`--quiet\`: Suppress output except errors

After completion, summarize:
- Number of files analyzed and any failures
- Number of directories documented
- Root and per-package documents generated
</execution>`,
  },

  update: {
    description: 'Incrementally update documentation for changed files',
    argumentHint: '[path] [--uncommitted] [--dry-run] [--budget N] [--concurrency N] [--verbose] [--quiet] [--fail-fast] [--debug] [--trace]',
    content: `Update documentation for files that changed since last run.

<execution>
Run the agents-reverse-engineer update command:

\`\`\`bash
npx agents-reverse-engineer@latest update $ARGUMENTS
\`\`\`

**Options:**
- \`--uncommitted\`: Include staged but uncommitted changes
- \`--dry-run\`: Show what would be updated without writing
- \`--budget N\`: Override token budget
- \`--concurrency N\`: Control number of parallel AI calls (default: 5)
- \`--fail-fast\`: Stop on first file analysis failure
- \`--debug\`: Show AI prompts and backend details
- \`--trace\`: Enable concurrency tracing to \`.agents-reverse-engineer/traces/\`
- \`--verbose\`: Show detailed output
- \`--quiet\`: Suppress output except errors

After completion, summarize:
- Files updated
- Files unchanged
- Any orphaned docs cleaned up
</execution>`,
  },

  init: {
    description: 'Initialize agents-reverse-engineer configuration',
    argumentHint: '',
    content: `Initialize agents-reverse-engineer configuration in this project.

<execution>
Run the agents-reverse-engineer init command:

\`\`\`bash
npx agents-reverse-engineer@latest init
\`\`\`

This creates \`.agents-reverse-engineer/config.yaml\` configuration file.
</execution>`,
  },

  discover: {
    description: 'Discover files in codebase',
    argumentHint: '[path] [--plan] [--show-excluded] [--quiet]',
    content: `List files that would be analyzed for documentation.

<execution>
## STRICT RULES - VIOLATION IS FORBIDDEN

1. Run ONLY this exact command: \`npx agents-reverse-engineer@latest discover $ARGUMENTS\`
2. DO NOT add \`--plan\` unless user typed \`--plan\`
3. DO NOT add ANY flags the user did not explicitly type
4. If user typed nothing after \`COMMAND_PREFIXdiscover\`, run with ZERO flags

\`\`\`bash
npx agents-reverse-engineer@latest discover $ARGUMENTS
\`\`\`

Report number of files found.
</execution>`,
  },

  clean: {
    description: 'Delete all generated documentation artifacts (.sum, AGENTS.md, plan)',
    argumentHint: '[--dry-run]',
    content: `Remove all documentation artifacts generated by agents-reverse-engineer.

<execution>
## What Gets Deleted

1. **Plan file**: \`.agents-reverse-engineer/GENERATION-PLAN.md\`
2. **Summary files**: All \`*.sum\` files
3. **Directory docs**: All \`AGENTS.md\` files
4. **Root docs**: \`CLAUDE.md\`, \`ARCHITECTURE.md\`
5. **Per-package docs**: \`STACK.md\`, \`STRUCTURE.md\`, \`CONVENTIONS.md\`, \`TESTING.md\`, \`INTEGRATIONS.md\`, \`CONCERNS.md\`

## Dry Run (Preview)

First, show what would be deleted:

\`\`\`bash
echo "=== Files to delete ===" && \\
find . -name "*.sum" -not -path "./node_modules/*" -not -path "./.git/*" 2>/dev/null && \\
find . -name "AGENTS.md" -not -path "./node_modules/*" -not -path "./.git/*" 2>/dev/null && \\
find . \\( -name "STACK.md" -o -name "STRUCTURE.md" -o -name "CONVENTIONS.md" -o -name "TESTING.md" -o -name "INTEGRATIONS.md" -o -name "CONCERNS.md" \\) -not -path "./node_modules/*" -not -path "./.git/*" 2>/dev/null && \\
ls -la CLAUDE.md ARCHITECTURE.md .agents-reverse-engineer/GENERATION-PLAN.md 2>/dev/null || true
\`\`\`

Report the count of files that would be deleted.

If user passed \`--dry-run\`, stop here.

## Execute Deletion

After confirming with the user (or if no --dry-run flag):

\`\`\`bash
find . -name "*.sum" -not -path "./node_modules/*" -not -path "./.git/*" -delete 2>/dev/null
find . -name "AGENTS.md" -not -path "./node_modules/*" -not -path "./.git/*" -delete 2>/dev/null
find . \\( -name "STACK.md" -o -name "STRUCTURE.md" -o -name "CONVENTIONS.md" -o -name "TESTING.md" -o -name "INTEGRATIONS.md" -o -name "CONCERNS.md" \\) -not -path "./node_modules/*" -not -path "./.git/*" -delete 2>/dev/null
rm -f CLAUDE.md ARCHITECTURE.md
rm -f .agents-reverse-engineer/GENERATION-PLAN.md
\`\`\`

Report:
- Number of .sum files deleted
- Number of AGENTS.md files deleted
- Root documents deleted
- Per-package documents deleted
- Plan file deleted

Suggest running \`COMMAND_PREFIXgenerate\` to start fresh.
</execution>`,
  },

  help: {
    description: 'Show available ARE commands and usage guide',
    argumentHint: '',
    // Content uses COMMAND_PREFIX placeholder, replaced per platform
    content: `<objective>
Display the complete ARE command reference.

Output ONLY the reference content below. Do NOT add:
- Project-specific analysis
- Git status or file context
- Next-step suggestions
- Any commentary beyond the reference
</objective>

<reference>
# agents-reverse-engineer (ARE) Command Reference

**ARE** generates AI-friendly documentation for codebases, creating structured summaries optimized for AI assistants.

## Quick Start

1. \`COMMAND_PREFIXinit\` — Create configuration file
2. \`COMMAND_PREFIXgenerate\` — Generate documentation for the codebase
3. \`COMMAND_PREFIXupdate\` — Keep docs in sync after code changes

## Commands Reference

### \`COMMAND_PREFIXinit\`
Initialize configuration in this project.

Creates \`.agents-reverse-engineer/config.yaml\` with customizable settings.

**Usage:** \`COMMAND_PREFIXinit\`
**CLI:** \`npx are init\`

---

### \`COMMAND_PREFIXdiscover\`
Discover files that would be analyzed for documentation.

**Options:**
| Flag | Description |
|------|-------------|
| \`[path]\` | Target directory (default: current directory) |
| \`--plan\` | Generate \`GENERATION-PLAN.md\` execution plan |
| \`--show-excluded\` | List excluded files with reasons |
| \`--quiet, -q\` | Suppress output except errors |

**Usage:**
- \`COMMAND_PREFIXdiscover\` — List discoverable files
- \`COMMAND_PREFIXdiscover --plan\` — Create execution plan for generate
- \`COMMAND_PREFIXdiscover --show-excluded\` — Debug exclusion rules

**CLI:**
\`\`\`bash
npx are discover
npx are discover --plan
npx are discover ./src --show-excluded
\`\`\`

---

### \`COMMAND_PREFIXgenerate\`
Generate comprehensive documentation for the codebase.

**Options:**
| Flag | Description |
|------|-------------|
| \`[path]\` | Target directory (default: current directory) |
| \`--budget N\` | Override token budget (default: from config) |
| \`--concurrency N\` | Number of concurrent AI calls (default: 5) |
| \`--dry-run\` | Show what would be generated without writing |
| \`--fail-fast\` | Stop on first file analysis failure |
| \`--debug\` | Show AI prompts and backend details |
| \`--trace\` | Enable concurrency tracing to \`.agents-reverse-engineer/traces/\` |
| \`--verbose, -v\` | Show detailed task breakdown |
| \`--quiet, -q\` | Suppress output except errors |

**Usage:**
- \`COMMAND_PREFIXgenerate\` — Generate docs
- \`COMMAND_PREFIXgenerate --dry-run\` — Preview without writing
- \`COMMAND_PREFIXgenerate --concurrency 3\` — Limit parallel AI calls

**CLI:**
\`\`\`bash
npx are generate
npx are generate --dry-run
npx are generate --budget 50000
npx are generate ./my-project --concurrency 3
npx are generate --debug --trace
\`\`\`

**How it works:**
1. Discovers files, applies filters, detects file types, and creates a generation plan
2. Analyzes each file via concurrent AI calls, writes \`.sum\` summary files
3. Generates \`AGENTS.md\` for each directory (post-order traversal)
4. Creates root documents: \`CLAUDE.md\`, \`ARCHITECTURE.md\` (if 20+ files)
5. Creates per-package documents at each manifest location: \`STACK.md\`, \`STRUCTURE.md\`, \`CONVENTIONS.md\`, \`TESTING.md\`, \`INTEGRATIONS.md\`, \`CONCERNS.md\`

---

### \`COMMAND_PREFIXupdate\`
Incrementally update documentation for changed files.

**Options:**
| Flag | Description |
|------|-------------|
| \`[path]\` | Target directory (default: current directory) |
| \`--uncommitted\` | Include staged but uncommitted changes |
| \`--dry-run\` | Show what would be updated without writing |
| \`--budget N\` | Override token budget |
| \`--concurrency N\` | Number of concurrent AI calls (default: 5) |
| \`--fail-fast\` | Stop on first file analysis failure |
| \`--debug\` | Show AI prompts and backend details |
| \`--trace\` | Enable concurrency tracing to \`.agents-reverse-engineer/traces/\` |
| \`--verbose, -v\` | Show detailed output |
| \`--quiet, -q\` | Suppress output except errors |

**Usage:**
- \`COMMAND_PREFIXupdate\` — Update docs for committed changes
- \`COMMAND_PREFIXupdate --uncommitted\` — Include uncommitted changes

**CLI:**
\`\`\`bash
npx are update
npx are update --uncommitted --verbose
npx are update --dry-run
npx are update ./my-project --concurrency 3
\`\`\`

---

### \`COMMAND_PREFIXclean\`
Remove all generated documentation artifacts.

**Options:**
| Flag | Description |
|------|-------------|
| \`--dry-run\` | Show what would be deleted without deleting |

**What gets deleted:**
- \`.agents-reverse-engineer/GENERATION-PLAN.md\`
- All \`*.sum\` files
- All \`AGENTS.md\` files
- Root docs: \`CLAUDE.md\`, \`ARCHITECTURE.md\`
- Per-package docs: \`STACK.md\`, \`STRUCTURE.md\`, \`CONVENTIONS.md\`, \`TESTING.md\`, \`INTEGRATIONS.md\`, \`CONCERNS.md\`

**Usage:**
- \`COMMAND_PREFIXclean --dry-run\` — Preview deletions
- \`COMMAND_PREFIXclean\` — Delete all artifacts

---

### \`COMMAND_PREFIXhelp\`
Show this command reference.

## CLI Installation

Install ARE commands to your AI assistant:

\`\`\`bash
npx agents-reverse-engineer install              # Interactive mode
npx agents-reverse-engineer install --runtime claude -g  # Global Claude
npx agents-reverse-engineer install --runtime claude -l  # Local project
npx agents-reverse-engineer install --runtime all -g     # All runtimes
\`\`\`

**Install/Uninstall Options:**
| Flag | Description |
|------|-------------|
| \`--runtime <name>\` | Target: \`claude\`, \`opencode\`, \`gemini\`, \`all\` |
| \`-g, --global\` | Install to global config directory |
| \`-l, --local\` | Install to current project directory |
| \`--force\` | Overwrite existing files (install only) |

## Configuration

**File:** \`.agents-reverse-engineer/config.yaml\`

\`\`\`yaml
# Exclusion patterns
exclude:
  patterns:
    - "**/*.test.ts"
    - "**/__mocks__/**"
  vendorDirs:
    - node_modules
    - dist
    - .git
  binaryExtensions:
    - .png
    - .jpg
    - .pdf

# Options
options:
  followSymlinks: false
  maxFileSize: 100000

# Output settings
output:
  verbose: false
  colors: true

# Generation settings
generation:
  tokenBudget: 50000
\`\`\`

## Generated Files

### Per Source File

**\`*.sum\`** — File summaries with YAML frontmatter + detailed prose.

\`\`\`yaml
---
file_type: service
generated_at: 2025-01-15T10:30:00Z
content_hash: abc123...
purpose: Handles user authentication and session management
public_interface: [login(), logout(), refreshToken(), AuthService]
dependencies: [express, jsonwebtoken, ./user-model]
patterns: [singleton, factory, observer]
related_files: [./types.ts, ./middleware.ts]
---

<300-500 word summary covering implementation, patterns, edge cases>
\`\`\`

### Per Directory

**\`AGENTS.md\`** — Directory overview synthesized from \`.sum\` files. Groups files by purpose and links to subdirectories.

### Root Documents

| File | Purpose |
|------|---------|
| \`CLAUDE.md\` | Project entry point — synthesizes all AGENTS.md |
| \`ARCHITECTURE.md\` | System design, layers, data flow (if 20+ files) |

### Per-Package Documents (at each manifest file location)

Generated alongside \`package.json\`, \`requirements.txt\`, \`Cargo.toml\`, etc.:

| File | Purpose |
|------|---------|
| \`STACK.md\` | Technology stack from manifest |
| \`STRUCTURE.md\` | Codebase structure and organization |
| \`CONVENTIONS.md\` | Coding conventions and patterns |
| \`TESTING.md\` | Test setup and patterns |
| \`INTEGRATIONS.md\` | External services and APIs |
| \`CONCERNS.md\` | Technical debt and known issues |

In monorepos, these appear in each package directory (e.g., \`packages/api/STACK.md\`).

## Common Workflows

**Initial documentation:**
\`\`\`
COMMAND_PREFIXinit
COMMAND_PREFIXgenerate
\`\`\`

**After code changes:**
\`\`\`
COMMAND_PREFIXupdate
\`\`\`

**Full regeneration:**
\`\`\`
COMMAND_PREFIXclean
COMMAND_PREFIXgenerate
\`\`\`

**Preview before generating:**
\`\`\`
COMMAND_PREFIXdiscover --show-excluded  # Check exclusions
COMMAND_PREFIXgenerate --dry-run         # Preview generation
\`\`\`

## Tips

- **Large codebases**: Use \`--budget N\` to limit token usage per run
- **Custom exclusions**: Edit \`.agents-reverse-engineer/config.yaml\` to skip files
- **Hook auto-update**: Install creates a session-end hook that auto-runs update

## Resources

- **Repository:** https://github.com/GeoloeG-IsT/agents-reverse-engineer
- **Update:** \`npx agents-reverse-engineer@latest install --force\`
</reference>`,
  },
} as const;

// =============================================================================
// Platform-specific template generators
// =============================================================================

type Platform = 'claude' | 'opencode' | 'gemini';

interface PlatformConfig {
  commandPrefix: string; // /are- (claude, opencode) or /are: (gemini)
  pathPrefix: string; // .claude/commands/are/ or .opencode/commands/ etc
  filenameSeparator: string; // . or -
  extraFrontmatter?: string; // e.g., "agent: build" for OpenCode
  usesName: boolean; // Claude uses "name:" in frontmatter
}

const PLATFORM_CONFIGS: Record<Platform, PlatformConfig> = {
  claude: {
    commandPrefix: '/are-',
    pathPrefix: '.claude/skills/',
    filenameSeparator: '.',
    usesName: true,
  },
  opencode: {
    commandPrefix: '/are-',
    pathPrefix: '.opencode/commands/',
    filenameSeparator: '-',
    extraFrontmatter: 'agent: build',
    usesName: false,
  },
  gemini: {
    commandPrefix: '/are-',
    pathPrefix: '.gemini/commands/',
    filenameSeparator: '-',
    usesName: false,
  },
};

function buildFrontmatter(
  platform: Platform,
  commandName: string,
  description: string
): string {
  const config = PLATFORM_CONFIGS[platform];
  const lines = ['---'];

  if (config.usesName) {
    lines.push(`name: are-${commandName}`);
  }

  lines.push(`description: ${description}`);

  if (config.extraFrontmatter) {
    lines.push(config.extraFrontmatter);
  }

  lines.push('---');
  return lines.join('\n');
}

/**
 * Build TOML content for Gemini CLI commands
 *
 * Gemini uses TOML format with description and prompt fields.
 * See: https://geminicli.com/docs/cli/custom-commands/
 */
function buildGeminiToml(
  commandName: string,
  command: (typeof COMMANDS)[keyof typeof COMMANDS]
): string {
  const config = PLATFORM_CONFIGS.gemini;
  // Replace command prefix placeholder in content
  const promptContent = command.content.replace(/COMMAND_PREFIX/g, config.commandPrefix);

  // Build TOML content
  // Use triple quotes for multi-line prompt
  const lines = [`description = "${command.description}"`];

  if (command.argumentHint) {
    lines.push(`# Arguments: ${command.argumentHint}`);
  }

  lines.push(`prompt = """`);
  lines.push(promptContent);
  lines.push(`"""`);

  return lines.join('\n');
}

function buildTemplate(
  platform: Platform,
  commandName: string,
  command: (typeof COMMANDS)[keyof typeof COMMANDS]
): IntegrationTemplate {
  const config = PLATFORM_CONFIGS[platform];

  // Platform-specific file naming:
  // - Claude: .claude/skills/are-{command}/SKILL.md
  // - OpenCode: .opencode/commands/are-{command}.md
  // - Gemini: .gemini/commands/are-{command}.toml (TOML format)
  if (platform === 'gemini') {
    const filename = `are-${commandName}.toml`;
    const path = `${config.pathPrefix}${filename}`;
    const content = buildGeminiToml(commandName, command);

    return {
      filename,
      path,
      content: `${content}\n`,
    };
  }

  const filename = platform === 'claude' ? 'SKILL.md' : `are-${commandName}.md`;
  const path =
    platform === 'claude'
      ? `${config.pathPrefix}are-${commandName}/${filename}`
      : `${config.pathPrefix}${filename}`;

  const frontmatter = buildFrontmatter(
    platform,
    commandName,
    command.description
  );

  // Replace command prefix placeholder in help content
  const content = command.content.replace(/COMMAND_PREFIX/g, config.commandPrefix);

  return {
    filename,
    path,
    content: `${frontmatter}\n\n${content}\n`,
  };
}

function getTemplatesForPlatform(platform: Platform): IntegrationTemplate[] {
  return Object.entries(COMMANDS).map(([name, command]) =>
    buildTemplate(platform, name, command)
  );
}

// =============================================================================
// Public API
// =============================================================================

/**
 * Get Claude Code command file templates
 */
export function getClaudeTemplates(): IntegrationTemplate[] {
  return getTemplatesForPlatform('claude');
}

/**
 * Get OpenCode command file templates
 */
export function getOpenCodeTemplates(): IntegrationTemplate[] {
  return getTemplatesForPlatform('opencode');
}

/**
 * Get Gemini CLI command file templates
 */
export function getGeminiTemplates(): IntegrationTemplate[] {
  return getTemplatesForPlatform('gemini');
}

