/**
 * Template generators for AI coding assistant integration files
 *
 * Generates command file templates for Claude Code, OpenCode, Gemini CLI, and session hooks.
 */

import type { IntegrationTemplate } from './types.js';

// =============================================================================
// Shared Command Content
// =============================================================================

const COMMANDS = {
  generate: {
    description: 'Generate AI-friendly documentation for the entire codebase',
    argumentHint: '[path] [--dry-run] [--concurrency N] [--fail-fast] [--debug] [--trace]',
    content: `Generate comprehensive documentation for this codebase using agents-reverse-engineer.

<execution>
Run the agents-reverse-engineer generate command:

\`\`\`bash
npx agents-reverse-engineer@latest generate $ARGUMENTS
\`\`\`

This executes a three-phase pipeline:

1. **Discovery & Planning**: Walks the directory tree, applies filters (gitignore, vendor, binary, custom), detects file types, and creates a generation plan.

2. **File Analysis** (concurrent): Analyzes each source file via AI and writes \`.sum\` summary files with YAML frontmatter (\`content_hash\`, \`file_type\`, \`purpose\`, \`public_interface\`, \`dependencies\`, \`patterns\`).

3. **Directory & Root Documents** (sequential):
   - Generates \`AGENTS.md\` per directory in post-order traversal (deepest first, so child summaries feed into parents)
   - Creates root document: \`CLAUDE.md\`

**Options:**
- \`--dry-run\`: Preview the plan without making AI calls
- \`--concurrency N\`: Control number of parallel AI calls (default: 5)
- \`--fail-fast\`: Stop on first file analysis failure
- \`--debug\`: Show AI prompts and backend details
- \`--trace\`: Enable concurrency tracing to \`.agents-reverse-engineer/traces/\`
After completion, summarize:
- Number of files analyzed and any failures
- Number of directories documented
- Root and per-package documents generated
</execution>`,
  },

  update: {
    description: 'Incrementally update documentation for changed files',
    argumentHint: '[path] [--uncommitted] [--dry-run] [--concurrency N] [--fail-fast] [--debug] [--trace]',
    content: `Update documentation for files that changed since last run.

<execution>
Run the agents-reverse-engineer update command:

\`\`\`bash
npx agents-reverse-engineer@latest update $ARGUMENTS
\`\`\`

**Options:**
- \`--uncommitted\`: Include staged but uncommitted changes
- \`--dry-run\`: Show what would be updated without writing
- \`--concurrency N\`: Control number of parallel AI calls (default: 5)
- \`--fail-fast\`: Stop on first file analysis failure
- \`--debug\`: Show AI prompts and backend details
- \`--trace\`: Enable concurrency tracing to \`.agents-reverse-engineer/traces/\`
After completion, summarize:
- Files updated
- Files unchanged
- Any orphaned docs cleaned up
</execution>`,
  },

  init: {
    description: 'Initialize agents-reverse-engineer configuration',
    argumentHint: '',
    content: `Initialize agents-reverse-engineer configuration in this project.

<execution>
Run the agents-reverse-engineer init command:

\`\`\`bash
npx agents-reverse-engineer@latest init
\`\`\`

This creates \`.agents-reverse-engineer/config.yaml\` configuration file.
</execution>`,
  },

  discover: {
    description: 'Discover files in codebase',
    argumentHint: '[path] [--debug] [--trace]',
    content: `List files that would be analyzed for documentation.

<execution>
## STRICT RULES - VIOLATION IS FORBIDDEN

1. Run ONLY this exact command: \`npx agents-reverse-engineer@latest discover $ARGUMENTS\`
2. DO NOT add ANY flags the user did not explicitly type
3. If user typed nothing after \`COMMAND_PREFIXdiscover\`, run with ZERO flags

\`\`\`bash
npx agents-reverse-engineer@latest discover $ARGUMENTS
\`\`\`

Report number of files found.
</execution>`,
  },

  clean: {
    description: 'Delete all generated documentation artifacts (.sum, AGENTS.md, plan)',
    argumentHint: '[path] [--dry-run]',
    content: `Remove all documentation artifacts generated by agents-reverse-engineer.

<execution>
## STRICT RULES - VIOLATION IS FORBIDDEN

1. Run ONLY this exact command: \`npx agents-reverse-engineer@latest clean $ARGUMENTS\`
2. DO NOT add ANY flags the user did not explicitly type
3. If user typed nothing after \`COMMAND_PREFIXclean\`, run with ZERO flags

\`\`\`bash
npx agents-reverse-engineer@latest clean $ARGUMENTS
\`\`\`

Report number of files deleted.
</execution>`,
  },

  specify: {
    description: 'Generate project specification from AGENTS.md docs',
    argumentHint: '[path] [--dry-run] [--output <path>] [--multi-file] [--force] [--debug] [--trace]',
    content: `Generate a project specification from existing AGENTS.md documentation.

<execution>
Run the agents-reverse-engineer specify command:

\`\`\`bash
npx agents-reverse-engineer@latest specify $ARGUMENTS
\`\`\`

This collects all AGENTS.md files, synthesizes them via AI, and writes a comprehensive project specification.

If no AGENTS.md files exist, it will auto-run \`generate\` first.

**Options:**
- \`--dry-run\`: Show input statistics without making AI calls
- \`--output <path>\`: Custom output path (default: specs/SPEC.md)
- \`--multi-file\`: Split specification into multiple files
- \`--force\`: Overwrite existing specification
- \`--debug\`: Show AI prompts and backend details
- \`--trace\`: Enable concurrency tracing to \`.agents-reverse-engineer/traces/\`
After completion, summarize:
- Number of AGENTS.md files collected
- Output file(s) written
</execution>`,
  },

  help: {
    description: 'Show available ARE commands and usage guide',
    argumentHint: '',
    // Content uses COMMAND_PREFIX placeholder, replaced per platform
    content: `<objective>
Display the complete ARE command reference.

Output ONLY the reference content below. Do NOT add:
- Project-specific analysis
- Git status or file context
- Next-step suggestions
- Any commentary beyond the reference
</objective>

<reference>
# agents-reverse-engineer (ARE) Command Reference

**ARE** generates AI-friendly documentation for codebases, creating structured summaries optimized for AI assistants.

## Quick Start

1. \`COMMAND_PREFIXinit\` — Create configuration file
2. \`COMMAND_PREFIXgenerate\` — Generate documentation for the codebase
3. \`COMMAND_PREFIXupdate\` — Keep docs in sync after code changes

## Commands Reference

### \`COMMAND_PREFIXinit\`
Initialize configuration in this project.

Creates \`.agents-reverse-engineer/config.yaml\` with customizable settings.

**Usage:** \`COMMAND_PREFIXinit\`
**CLI:** \`npx are init\`

---

### \`COMMAND_PREFIXdiscover\`
Discover files that would be analyzed for documentation.

Shows included files, excluded files with reasons, and generates a \`GENERATION-PLAN.md\` execution plan.

**Options:**
| Flag | Description |
|------|-------------|
| \`[path]\` | Target directory (default: current directory) |
| \`--debug\` | Show verbose debug output |
| \`--trace\` | Enable concurrency tracing to \`.agents-reverse-engineer/traces/\` |
**Usage:**
- \`COMMAND_PREFIXdiscover\` — Discover files and generate execution plan

**CLI:**
\`\`\`bash
npx are discover
npx are discover ./src
\`\`\`

---

### \`COMMAND_PREFIXgenerate\`
Generate comprehensive documentation for the codebase.

**Options:**
| Flag | Description |
|------|-------------|
| \`[path]\` | Target directory (default: current directory) |
| \`--concurrency N\` | Number of concurrent AI calls (default: 5) |
| \`--dry-run\` | Show what would be generated without writing |
| \`--fail-fast\` | Stop on first file analysis failure |
| \`--debug\` | Show AI prompts and backend details |
| \`--trace\` | Enable concurrency tracing to \`.agents-reverse-engineer/traces/\` |
**Usage:**
- \`COMMAND_PREFIXgenerate\` — Generate docs
- \`COMMAND_PREFIXgenerate --dry-run\` — Preview without writing
- \`COMMAND_PREFIXgenerate --concurrency 3\` — Limit parallel AI calls

**CLI:**
\`\`\`bash
npx are generate
npx are generate --dry-run
npx are generate ./my-project --concurrency 3
npx are generate --debug --trace
\`\`\`

**How it works:**
1. Discovers files, applies filters, detects file types, and creates a generation plan
2. Analyzes each file via concurrent AI calls, writes \`.sum\` summary files
3. Generates \`AGENTS.md\` for each directory (post-order traversal)
4. Creates root document: \`CLAUDE.md\`

---

### \`COMMAND_PREFIXupdate\`
Incrementally update documentation for changed files.

**Options:**
| Flag | Description |
|------|-------------|
| \`[path]\` | Target directory (default: current directory) |
| \`--uncommitted\` | Include staged but uncommitted changes |
| \`--dry-run\` | Show what would be updated without writing |
| \`--concurrency N\` | Number of concurrent AI calls (default: 5) |
| \`--fail-fast\` | Stop on first file analysis failure |
| \`--debug\` | Show AI prompts and backend details |
| \`--trace\` | Enable concurrency tracing to \`.agents-reverse-engineer/traces/\` |
**Usage:**
- \`COMMAND_PREFIXupdate\` — Update docs for committed changes
- \`COMMAND_PREFIXupdate --uncommitted\` — Include uncommitted changes

**CLI:**
\`\`\`bash
npx are update
npx are update --uncommitted
npx are update --dry-run
npx are update ./my-project --concurrency 3
\`\`\`

---

### \`COMMAND_PREFIXspecify\`
Generate a project specification from AGENTS.md documentation.

Collects all AGENTS.md files, synthesizes them via AI, and writes a comprehensive project specification. Auto-runs \`generate\` if no AGENTS.md files exist.

**Options:**
| Flag | Description |
|------|-------------|
| \`[path]\` | Target directory (default: current directory) |
| \`--output <path>\` | Custom output path (default: specs/SPEC.md) |
| \`--multi-file\` | Split specification into multiple files |
| \`--force\` | Overwrite existing specification |
| \`--dry-run\` | Show input statistics without making AI calls |
| \`--debug\` | Show AI prompts and backend details |
| \`--trace\` | Enable concurrency tracing to \`.agents-reverse-engineer/traces/\` |
**Usage:**
- \`COMMAND_PREFIXspecify\` — Generate specification
- \`COMMAND_PREFIXspecify --dry-run\` — Preview without calling AI
- \`COMMAND_PREFIXspecify --output ./docs/spec.md --force\` — Custom output path

**CLI:**
\`\`\`bash
npx are specify
npx are specify --dry-run
npx are specify --output ./docs/spec.md --force
npx are specify --multi-file
\`\`\`

---

### \`COMMAND_PREFIXclean\`
Remove all generated documentation artifacts.

**Options:**
| Flag | Description |
|------|-------------|
| \`--dry-run\` | Show what would be deleted without deleting |

**What gets deleted:**
- \`.agents-reverse-engineer/GENERATION-PLAN.md\`
- All \`*.sum\` files
- All \`AGENTS.md\` files
- Root docs: \`CLAUDE.md\`

**Usage:**
- \`COMMAND_PREFIXclean --dry-run\` — Preview deletions
- \`COMMAND_PREFIXclean\` — Delete all artifacts

**CLI:**
\`\`\`bash
npx are clean --dry-run
npx are clean
\`\`\`

---

### \`COMMAND_PREFIXhelp\`
Show this command reference.

## CLI Installation

Install ARE commands to your AI assistant:

\`\`\`bash
npx agents-reverse-engineer install              # Interactive mode
npx agents-reverse-engineer install --runtime claude -g  # Global Claude
npx agents-reverse-engineer install --runtime claude -l  # Local project
npx agents-reverse-engineer install --runtime all -g     # All runtimes
\`\`\`

**Install/Uninstall Options:**
| Flag | Description |
|------|-------------|
| \`--runtime <name>\` | Target: \`claude\`, \`opencode\`, \`gemini\`, \`all\` |
| \`-g, --global\` | Install to global config directory |
| \`-l, --local\` | Install to current project directory |
| \`--force\` | Overwrite existing files (install only) |

## Configuration

**File:** \`.agents-reverse-engineer/config.yaml\`

\`\`\`yaml
# Exclusion patterns
exclude:
  patterns:
    - "**/*.test.ts"
    - "**/__mocks__/**"
  vendorDirs:
    - node_modules
    - dist
    - .git
  binaryExtensions:
    - .png
    - .jpg
    - .pdf

# Options
options:
  followSymlinks: false
  maxFileSize: 100000

# Output settings
output:
  colors: true
\`\`\`

## Generated Files

### Per Source File

**\`*.sum\`** — File summaries with YAML frontmatter + detailed prose.

\`\`\`yaml
---
file_type: service
generated_at: 2025-01-15T10:30:00Z
content_hash: abc123...
purpose: Handles user authentication and session management
public_interface: [login(), logout(), refreshToken(), AuthService]
dependencies: [express, jsonwebtoken, ./user-model]
patterns: [singleton, factory, observer]
related_files: [./types.ts, ./middleware.ts]
---

<300-500 word summary covering implementation, patterns, edge cases>
\`\`\`

### Per Directory

**\`AGENTS.md\`** — Directory overview synthesized from \`.sum\` files. Groups files by purpose and links to subdirectories.

### Root Documents

| File | Purpose |
|------|---------|
| \`CLAUDE.md\` | Project entry point — synthesizes all AGENTS.md |

## Common Workflows

**Initial documentation:**
\`\`\`
COMMAND_PREFIXinit
COMMAND_PREFIXgenerate
\`\`\`

**After code changes:**
\`\`\`
COMMAND_PREFIXupdate
\`\`\`

**Full regeneration:**
\`\`\`
COMMAND_PREFIXclean
COMMAND_PREFIXgenerate
\`\`\`

**Preview before generating:**
\`\`\`
COMMAND_PREFIXdiscover                   # Check files and exclusions
COMMAND_PREFIXgenerate --dry-run         # Preview generation
\`\`\`

## Tips

- **Custom exclusions**: Edit \`.agents-reverse-engineer/config.yaml\` to skip files
- **Hook auto-update**: Install creates a session-end hook that auto-runs update

## Resources

- **Repository:** https://github.com/GeoloeG-IsT/agents-reverse-engineer
- **Update:** \`npx agents-reverse-engineer@latest install --force\`
</reference>`,
  },
} as const;

// =============================================================================
// Platform-specific template generators
// =============================================================================

type Platform = 'claude' | 'opencode' | 'gemini';

interface PlatformConfig {
  commandPrefix: string; // /are- (claude, opencode) or /are: (gemini)
  pathPrefix: string; // .claude/commands/are/ or .opencode/commands/ etc
  filenameSeparator: string; // . or -
  extraFrontmatter?: string; // e.g., "agent: build" for OpenCode
  usesName: boolean; // Claude uses "name:" in frontmatter
}

const PLATFORM_CONFIGS: Record<Platform, PlatformConfig> = {
  claude: {
    commandPrefix: '/are-',
    pathPrefix: '.claude/skills/',
    filenameSeparator: '.',
    usesName: true,
  },
  opencode: {
    commandPrefix: '/are-',
    pathPrefix: '.opencode/commands/',
    filenameSeparator: '-',
    extraFrontmatter: 'agent: build',
    usesName: false,
  },
  gemini: {
    commandPrefix: '/are-',
    pathPrefix: '.gemini/commands/',
    filenameSeparator: '-',
    usesName: false,
  },
};

function buildFrontmatter(
  platform: Platform,
  commandName: string,
  description: string
): string {
  const config = PLATFORM_CONFIGS[platform];
  const lines = ['---'];

  if (config.usesName) {
    lines.push(`name: are-${commandName}`);
  }

  lines.push(`description: ${description}`);

  if (config.extraFrontmatter) {
    lines.push(config.extraFrontmatter);
  }

  lines.push('---');
  return lines.join('\n');
}

/**
 * Build TOML content for Gemini CLI commands
 *
 * Gemini uses TOML format with description and prompt fields.
 * See: https://geminicli.com/docs/cli/custom-commands/
 */
function buildGeminiToml(
  commandName: string,
  command: (typeof COMMANDS)[keyof typeof COMMANDS]
): string {
  const config = PLATFORM_CONFIGS.gemini;
  // Replace command prefix placeholder in content
  const promptContent = command.content.replace(/COMMAND_PREFIX/g, config.commandPrefix);

  // Build TOML content
  // Use triple quotes for multi-line prompt
  const lines = [`description = "${command.description}"`];

  if (command.argumentHint) {
    lines.push(`# Arguments: ${command.argumentHint}`);
  }

  lines.push(`prompt = """`);
  lines.push(promptContent);
  lines.push(`"""`);

  return lines.join('\n');
}

function buildTemplate(
  platform: Platform,
  commandName: string,
  command: (typeof COMMANDS)[keyof typeof COMMANDS]
): IntegrationTemplate {
  const config = PLATFORM_CONFIGS[platform];

  // Platform-specific file naming:
  // - Claude: .claude/skills/are-{command}/SKILL.md
  // - OpenCode: .opencode/commands/are-{command}.md
  // - Gemini: .gemini/commands/are-{command}.toml (TOML format)
  if (platform === 'gemini') {
    const filename = `are-${commandName}.toml`;
    const path = `${config.pathPrefix}${filename}`;
    const content = buildGeminiToml(commandName, command);

    return {
      filename,
      path,
      content: `${content}\n`,
    };
  }

  const filename = platform === 'claude' ? 'SKILL.md' : `are-${commandName}.md`;
  const path =
    platform === 'claude'
      ? `${config.pathPrefix}are-${commandName}/${filename}`
      : `${config.pathPrefix}${filename}`;

  const frontmatter = buildFrontmatter(
    platform,
    commandName,
    command.description
  );

  // Replace command prefix placeholder in help content
  const content = command.content.replace(/COMMAND_PREFIX/g, config.commandPrefix);

  return {
    filename,
    path,
    content: `${frontmatter}\n\n${content}\n`,
  };
}

function getTemplatesForPlatform(platform: Platform): IntegrationTemplate[] {
  return Object.entries(COMMANDS).map(([name, command]) =>
    buildTemplate(platform, name, command)
  );
}

// =============================================================================
// Public API
// =============================================================================

/**
 * Get Claude Code command file templates
 */
export function getClaudeTemplates(): IntegrationTemplate[] {
  return getTemplatesForPlatform('claude');
}

/**
 * Get OpenCode command file templates
 */
export function getOpenCodeTemplates(): IntegrationTemplate[] {
  return getTemplatesForPlatform('opencode');
}

/**
 * Get Gemini CLI command file templates
 */
export function getGeminiTemplates(): IntegrationTemplate[] {
  return getTemplatesForPlatform('gemini');
}

