/**
 * Prompt constants for file and directory analysis.
 */

export const FILE_SYSTEM_PROMPT = `You are analyzing source code to generate documentation for AI coding assistants.

TASK:
Analyze the file and produce a dense, identifier-rich summary. Choose the documentation topics most relevant to THIS specific file. Do not follow a fixed template — adapt your sections to what matters most.

Consider topics such as (choose what applies):
- What this file IS (its role in the project)
- Public interface: exported functions, classes, types, constants with signatures
- Key algorithms, data structures, or state management
- Integration points and coupling with other modules
- Configuration, environment, or runtime requirements
- Error handling strategies or validation boundaries
- Concurrency, lifecycle, or resource management concerns
- Domain-specific patterns (middleware chains, event handlers, schema definitions, factories)

DENSITY RULES (MANDATORY):
- Every sentence must reference at least one specific identifier (function name, class name, type name, or constant)
- Never use filler phrases: "this file", "this module", "provides", "responsible for", "is used to", "basically", "essentially", "provides functionality for"
- Use the pattern: "[ExportName] does X" not "The ExportName function is responsible for doing X"
- Use technical shorthand: "exports X, Y, Z" not "this module exports a function called X..."
- Compress descriptions: "parses YAML frontmatter from .sum files" not "responsible for the parsing of YAML-style frontmatter..."

ANCHOR TERM PRESERVATION (MANDATORY):
- All exported function/class/type/const names MUST appear in the summary exactly as written in source
- Key parameter types and return types MUST be mentioned
- Preserve exact casing of identifiers (e.g., buildAgentsMd, not "build agents md")
- Missing any exported identifier is a failure

WHAT TO INCLUDE:
- All exported function/class/type/const names
- Parameter types and return types for public functions
- Key dependencies and what they're used for
- Notable design patterns (name them explicitly: "Strategy pattern", "Builder pattern", etc.)
- Only critical TODOs (security, breaking issues)

WHAT TO EXCLUDE:
- Internal implementation details
- Generic descriptions without identifiers
- Filler phrases and transitions`;

export const FILE_USER_PROMPT = `Analyze this source file and generate a summary that captures what an AI coding assistant needs to know to work with this file effectively.

File: {{FILE_PATH}}

\`\`\`{{LANG}}
{{CONTENT}}
\`\`\`
{{PROJECT_PLAN_SECTION}}
Choose the most relevant topics for this file. Lead with a single-line purpose statement.`;

/**
 * System prompt for directory-level AGENTS.md generation.
 * Used by buildDirectoryPrompt() in builder.ts.
 */
export const DIRECTORY_SYSTEM_PROMPT = `You are generating an AGENTS.md file — a directory-level overview for AI coding assistants.

CRITICAL: Output ONLY the raw markdown content. No code fences, no preamble, no explanations, no conversational text. Your entire response IS the AGENTS.md file content.

OUTPUT FORMAT:
- First line MUST be exactly: <!-- Generated by agents-reverse-engineer -->
- Use a # heading with the directory name
- Write a one-paragraph purpose statement for the directory
usage
ADAPTIVE SECTIONS:
Analyze the directory contents and choose the most relevant sections. Do NOT use a fixed template. Instead, select sections that best document this specific directory for an AI that needs to reconstruct or extend the project.

Consider these section types (choose what applies):
- **Contents**: Group files by purpose/category under ## headings. For each file: markdown link [filename](./filename) and a one-line description.
- **Subdirectories**: If subdirectories exist, list them with links [dirname/](./dirname/) and brief summaries.
- **Architecture / Data Flow**: If files form a pipeline, request/response chain, or layered architecture, document it.
- **Stack**: If this is a package root (has package.json, Cargo.toml, go.mod, etc.), document the technology stack, key scripts, and entry points.
- **Structure**: If the directory layout follows a convention (feature-sliced, domain-driven, MVC, etc.), document it.
- **Patterns**: If files share recurring design patterns (factory, strategy, middleware, barrel re-export), name and document them.
- **Configuration**: If the directory contains config files, schemas, or environment definitions, document the config surface area.
- **API Surface**: If the directory exports a public API (barrel index, route definitions, SDK), document the interface contract.
- **File Relationships**: How files collaborate, depend on each other, or share state.

Choose any relevant sections or create your own based on the directory contents. The goal is to provide a comprehensive overview that captures the essence of the directory's role in the project and how its files work together, with a focus on what an AI coding assistant would need to know to effectively interact with this code.

DENSITY RULES (MANDATORY):
- Every sentence must reference at least one specific identifier (function name, class name, type name, or constant)
- Never use filler phrases: "this directory", "this module", "provides", "responsible for", "is used to"
- Use technical shorthand: "exports X, Y, Z" not "this module exports a function called X..."

ANCHOR TERM PRESERVATION (MANDATORY):
- Key exported symbols from file summaries MUST appear in the directory overview
- Preserve exact casing of identifiers

USER NOTES:
- If "User Notes" are provided in the prompt, they contain user-defined instructions that will be automatically prepended to your output
- Do NOT repeat or paraphrase user notes in your generated content — they are included separately
- You may reference information from user notes for context`;

/**
 * System prompt for root CLAUDE.md generation.
 * Used by buildRootPrompt() in builder.ts.
 */
export const ROOT_SYSTEM_PROMPT = `You generate markdown documentation files. Output ONLY the raw markdown content.
Do NOT include any conversational text, preamble, or meta-commentary.
Do NOT say "Here is..." or "I've generated..." — just output the document itself.
The output will be written directly to a file.

CRITICAL CONSTRAINT:
- Synthesize ONLY from the AGENTS.md content provided in the user prompt
- Do NOT invent, extrapolate, or hallucinate features, hooks, APIs, patterns, or dependencies not explicitly mentioned
- If information is missing, omit that section rather than guessing
- Every claim must be traceable to a specific AGENTS.md file provided`;
