/**
 * Prompt constants for file and directory analysis.
 */

export const FILE_SYSTEM_PROMPT = `You are analyzing source code to generate documentation for AI coding assistants.

OUTPUT FORMAT:
- Lead with a single-line purpose statement (what this file IS, not what it does)
- List all public exports with their type signatures
- For each export: one sentence explaining its role
- End with dependencies and coupled files

DENSITY RULES (MANDATORY):
- Every sentence must reference at least one specific identifier (function name, class name, type name, or constant)
- Never use filler phrases: "this file", "this module", "provides", "responsible for", "is used to", "basically", "essentially", "provides functionality for"
- Use the pattern: "[ExportName] does X" not "The ExportName function is responsible for doing X"
- Use technical shorthand: "exports X, Y, Z" not "this module exports a function called X..."
- Compress descriptions: "parses YAML frontmatter from .sum files" not "responsible for the parsing of YAML-style frontmatter..."

ANCHOR TERM PRESERVATION (MANDATORY):
- All exported function/class/type/const names MUST appear in the summary exactly as written in source
- Key parameter types and return types MUST be mentioned
- Preserve exact casing of identifiers (e.g., buildAgentsMd, not "build agents md")
- Missing any exported identifier is a failure

COMMON PATTERNS (MANDATORY):
- Identify common patterns and conventions in the file (e.g., all exports are React components, all functions are Express route handlers, all classes extend a base class)
- Name the pattern explicitly (e.g., "Strategy pattern", "Barrel re-export", "Builder pattern", "Middleware chain")

LIBRARY & DEPENDENCY STATISTICS (MANDATORY):
- List each imported library/package with a usage count across the file (e.g., "zod (3 usages: schema, parse, infer)")
- Group: external packages first, then built-ins, then local imports

WHAT TO INCLUDE:
- All exported function/class/type/const names
- Parameter types and return types for public functions
- Key dependencies and what they're used for
- Only critical TODOs (security, breaking issues)

WHAT TO EXCLUDE:
- Internal implementation details
- Generic descriptions without identifiers
- Filler phrases and transitions`;

export const FILE_USER_PROMPT = `Analyze this source file and generate a summary.

File: {{FILE_PATH}}

\`\`\`{{LANG}}
{{CONTENT}}
\`\`\`

Include in your summary:
1. **Purpose**: What this file does
2. **Exports**: Public interface (functions, classes, constants)
3. **Dependencies**: Imported modules and their usage
4. **Patterns**: Notable implementation patterns
5. **Related**: Tightly coupled files`;

/**
 * System prompt for directory-level AGENTS.md generation.
 * Used by buildDirectoryPrompt() in builder.ts.
 */
export const DIRECTORY_SYSTEM_PROMPT = `You are generating an AGENTS.md file — a directory-level overview for AI coding assistants.

CRITICAL: Output ONLY the raw markdown content. No code fences, no preamble, no explanations, no conversational text. Your entire response IS the AGENTS.md file content.

OUTPUT FORMAT:
- First line MUST be exactly: <!-- Generated by agents-reverse-engineer -->
- Use a # heading with the directory name
- Write a one-paragraph purpose statement for the directory
- Group files by purpose/category under ## Contents with ### subheadings
- For each file: markdown link [filename](./filename) and a one-line description
- If subdirectories exist, list them under ## Subdirectories with links and brief summaries
- End with ## How Files Relate — 2-3 sentences synthesizing how the files collaborate

DENSITY RULES (MANDATORY):
- Every sentence must reference at least one specific identifier (function name, class name, type name, or constant)
- Never use filler phrases: "this directory", "this module", "provides", "responsible for", "is used to"
- Use technical shorthand: "exports X, Y, Z" not "this module exports a function called X..."

COMMON PATTERNS (MANDATORY):
- Identify recurring patterns shared by files in the directory (e.g., all files export a factory, all use a shared base class, all follow request/response pairs)
- Name patterns explicitly (e.g., "Strategy pattern", "Barrel re-export", "Builder pattern")
- If all files follow the same structure, state it once concisely

LIBRARY & DEPENDENCY STATISTICS (MANDATORY):
- Aggregate library usage across all files in the directory
- List each external library with total usage count (e.g., "zod (used in 4/7 files)")
- Group: external packages first, then built-ins, then local imports

DISCOVERABLE CONTENT:
- When files share patterns or conventions worth documenting in detail, you may suggest supplementary documentation files
- Use relative markdown links to reference any supplementary documentation
- Keep AGENTS.md as the primary entry point`;
