/**
 * 36-frame golden circle animation frames
 *
 * Each frame is 6 lines x 16 chars representing a hollow ring
 * with a rotating highlight spot.
 *
 * Generated by scripts/generate-circle-frames.js
 */

export const GOLDEN_CIRCLE_FRAMES: string[] = [
  "    ....··::    \n  ...      ;oo  \n ..          OO \n ..          OO \n  ...      ;oo  \n    ....··::    ",
  "    .....···    \n  ...      :;;  \n ..          OO \n ..          OO \n  ...      ooO  \n    ...··::;    ",
  "    ......··    \n  ...      ::;  \n ..          oo \n ..          OO \n  ...      OOO  \n    ..··::;o    ",
  "    ........    \n  ...      ·::  \n ..          ;o \n ..          OO \n  ...      OOO  \n    .··::;oo    ",
  "    ........    \n  ...      ···  \n ..          ;; \n ..          oo \n  ...      OOO  \n    ··::;oOO    ",
  "    ........    \n  ...      ..·  \n ..          :: \n ..          oo \n  ..·      OOO  \n    ·::;oOOO    ",
  "    ........    \n  ...      ...  \n ..          ·· \n ..          ;; \n  ···      OOO  \n    :;;oOOOO    ",
  "    ........    \n  ...      ...  \n ..          ·· \n ..          :: \n  ··:      Ooo  \n    ;;oOOOOO    ",
  "    ........    \n  ...      ...  \n ..          .. \n ..          :· \n  :::      o;;  \n    ooOOOOOO    ",
  "    ........    \n  ...      ...  \n ..          .. \n ··          ·· \n  :;;      ;;:  \n    oOOOOOOo    ",
  "    ........    \n  ...      ...  \n ..          .. \n ·:          .. \n  ;;o      :::  \n    OOOOOOoo    ",
  "    ........    \n  ...      ...  \n ··          .. \n ::          .. \n  ooO      :··  \n    OOOOOo;;    ",
  "    ........    \n  ...      ...  \n ··          .. \n ;;          .. \n  OOO      ···  \n    OOOOo;;:    ",
  "    ........    \n  ·..      ...  \n ::          .. \n oo          .. \n  OOO      ·..  \n    OOOo;::·    ",
  "    ........    \n  ···      ...  \n ;;          .. \n oo          .. \n  OOO      ...  \n    OOo;::··    ",
  "    ........    \n  ::·      ...  \n o;          .. \n OO          .. \n  OOO      ...  \n    oo;::··.    ",
  "    ··......    \n  ;::      ...  \n oo          .. \n OO          .. \n  OOO      ...  \n    o;::··..    ",
  "    ···.....    \n  ;;:      ...  \n OO          .. \n OO          .. \n  Ooo      ...  \n    ;::··...    ",
  "    ::··....    \n  oo;      ...  \n OO          .. \n OO          .. \n  oo;      ...  \n    ::··....    ",
  "    ;::··...    \n  Ooo      ...  \n OO          .. \n OO          .. \n  ;;:      ...  \n    ···.....    ",
  "    o;::··..    \n  OOO      ...  \n OO          .. \n oo          .. \n  ;::      ...  \n    ··......    ",
  "    oo;::··.    \n  OOO      ...  \n OO          .. \n o;          .. \n  ::·      ...  \n    ........    ",
  "    OOo;::··    \n  OOO      ...  \n oo          .. \n ;;          .. \n  ···      ...  \n    ........    ",
  "    OOOo;::·    \n  OOO      ·..  \n oo          .. \n ::          .. \n  ·..      ...  \n    ........    ",
  "    OOOOo;;:    \n  OOO      ···  \n ;;          .. \n ··          .. \n  ...      ...  \n    ........    ",
  "    OOOOOo;;    \n  ooO      :··  \n ::          .. \n ··          .. \n  ...      ...  \n    ........    ",
  "    OOOOOOoo    \n  ;;o      :::  \n ·:          .. \n ..          .. \n  ...      ...  \n    ........    ",
  "    oOOOOOOo    \n  :;;      ;;:  \n ··          ·· \n ..          .. \n  ...      ...  \n    ........    ",
  "    ooOOOOOO    \n  :::      o;;  \n ..          :· \n ..          .. \n  ...      ...  \n    ........    ",
  "    ;;oOOOOO    \n  ··:      Ooo  \n ..          :: \n ..          ·· \n  ...      ...  \n    ........    ",
  "    :;;oOOOO    \n  ···      OOO  \n ..          ;; \n ..          ·· \n  ...      ...  \n    ........    ",
  "    ·::;oOOO    \n  ..·      OOO  \n ..          oo \n ..          :: \n  ...      ..·  \n    ........    ",
  "    ··::;oOO    \n  ...      OOO  \n ..          oo \n ..          ;; \n  ...      ···  \n    ........    ",
  "    .··::;oo    \n  ...      OOO  \n ..          OO \n ..          ;o \n  ...      ·::  \n    ........    ",
  "    ..··::;o    \n  ...      OOO  \n ..          OO \n ..          oo \n  ...      ::;  \n    ......··    ",
  "    ...··::;    \n  ...      ooO  \n ..          OO \n ..          OO \n  ...      :;;  \n    .....···    "
];

export const FRAME_WIDTH = 16;
export const FRAME_HEIGHT = 6;
